In [1]:
import pandas as pd

In [2]:
muestra=pd.read_csv('../data/muestra.csv')

muestra.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 107 entries, 0 to 106
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             107 non-null    int64
 1   salary_in_usd  107 non-null    int64
dtypes: int64(2)
memory usage: 1.8 KB

In [3]:
testeo=pd.read_csv('../data/testeo.csv')

testeo.head()

,work_year,experience_level,employment_type,job_title,salary,salary_currency,employee_residence,remote_ratio,company_location,company_size
0,2020,SE,FT,Machine Learning Scientist,260000,USD,JP,0,JP,S
1,2020,MI,FT,Lead Data Analyst,87000,USD,US,100,US,L
2,2020,MI,FT,Data Analyst,85000,USD,US,100,US,L
3,2020,MI,FT,Machine Learning Engineer,299000,CNY,CN,0,CN,M
4,2020,MI,FT,Product Data Analyst,450000,INR,IN,100,IN,L

In [4]:
salary=pd.read_csv('../data/salaries_data.csv')

salary.head()

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2022,SE,FT,Data Engineer,140250,USD,140250,US,100,US,M
1,2022,SE,FT,Data Engineer,135000,USD,135000,US,100,US,M
2,2021,MI,FT,BI Data Analyst,100000,USD,100000,US,100,US,M
3,2021,MI,CT,ML Engineer,270000,USD,270000,US,100,US,L
4,2021,MI,FT,Data Engineer,22000,EUR,26005,RO,0,US,L

In [5]:
import numpy as np

In [6]:
salary.drop(columns=['salary','salary_currency','employee_residence'], inplace=True)

In [7]:
testeo.drop(columns=['salary','salary_currency','employee_residence'], inplace=True)

In [8]:
salary.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   work_year         500 non-null    int64
 1   experience_level  500 non-null    object
 2   employment_type   500 non-null    object
 3   job_title         500 non-null    object
 4   salary_in_usd     500 non-null    int64
 5   remote_ratio      500 non-null    int64
 6   company_location  500 non-null    object
 7   company_size      500 non-null    object
dtypes: int64(3), object(5)
memory usage: 162.3 KB

In [9]:
testeo.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 107 entries, 0 to 106
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   work_year         107 non-null    int64
 1   experience_level  107 non-null    object
 2   employment_type   107 non-null    object
 3   job_title         107 non-null    object
 4   remote_ratio      107 non-null    int64
 5   company_location  107 non-null    object
 6   company_size      107 non-null    object
dtypes: int64(2), object(5)
memory usage: 34.1 KB

Modificamos la columna job_title. Nos quedamos con 4 variables

In [10]:
def job_title(x):
    if 'Machine' in x or 'ML' in x or 'Computer' in x:
        return 'Machine Learning'
    if 'Engineer' in x or 'Engineering' in x:
        return 'Data Engineer'
    if 'Analyst' in x or 'Analytics' in x:
        return 'Data Analyst'
    else:
        return 'Data Scientist'

In [11]:
salary.job_title=salary.job_title.apply(job_title)

In [12]:
testeo.job_title=testeo.job_title.apply(job_title)

Reemplazamos los valosres CT y FL por PT y FT respectivamente para quedarnos con esas 2 variables unicamente

In [13]:
salary.employment_type = salary.employment_type.replace('CT', 'PT')
salary.employment_type = salary.employment_type.replace('FL', 'FT')

In [14]:
testeo.employment_type = testeo.employment_type.replace('CT', 'PT')
testeo.employment_type = testeo.employment_type.replace('FL', 'FT')

In [15]:
salary.employment_type.unique()

array(['FT', 'PT'], dtype=object)

Le asignamos un valor

In [16]:
employment_type={'FT': 1, 'PT':0.5}

def cambio_employment(x):   
    return employment_type[x]

salary.employment_type=salary.employment_type.apply(lambda x: employment_type[x])

salary.head()

,work_year,experience_level,employment_type,job_title,salary_in_usd,remote_ratio,company_location,company_size
0,2022,SE,1.0,Data Engineer,140250,100,US,M
1,2022,SE,1.0,Data Engineer,135000,100,US,M
2,2021,MI,1.0,Data Analyst,100000,100,US,M
3,2021,MI,0.5,Machine Learning,270000,100,US,L
4,2021,MI,1.0,Data Engineer,26005,0,US,L

In [17]:
testeo.employment_type=testeo.employment_type.apply(lambda x: employment_type[x])

testeo.head()

,work_year,experience_level,employment_type,job_title,remote_ratio,company_location,company_size
0,2020,SE,1.0,Machine Learning,0,JP,S
1,2020,MI,1.0,Data Analyst,100,US,L
2,2020,MI,1.0,Data Analyst,100,US,L
3,2020,MI,1.0,Machine Learning,0,CN,M
4,2020,MI,1.0,Data Analyst,100,IN,L

In [18]:
salary.head()

,work_year,experience_level,employment_type,job_title,salary_in_usd,remote_ratio,company_location,company_size
0,2022,SE,1.0,Data Engineer,140250,100,US,M
1,2022,SE,1.0,Data Engineer,135000,100,US,M
2,2021,MI,1.0,Data Analyst,100000,100,US,M
3,2021,MI,0.5,Machine Learning,270000,100,US,L
4,2021,MI,1.0,Data Engineer,26005,0,US,L

Al nivel de experiencia le asignamos un valor diferente ya que entendemos que según tú experiencia ganas más

In [19]:
salary.groupby('experience_level').mean()

                    work_year  employment_type  salary_in_usd  remote_ratio
experience_level
EN                2020.938462         0.953846   59989.569231     70.769231
EX                2021.450000         0.975000  196078.850000     80.000000
MI                2021.267442         0.988372   90384.610465     65.116279
SE                2021.641975         0.997942  136341.794239     76.131687

In [20]:
experience_level={'SE': 7, 'MI': 5, 'EN': 3, 'EX':10}

def cambio_exp(x):   
    return experience_level[x]

salary.experience_level=salary.experience_level.apply(lambda x: experience_level[x])

salary.head()

,work_year,experience_level,employment_type,job_title,salary_in_usd,remote_ratio,company_location,company_size
0,2022,7,1.0,Data Engineer,140250,100,US,M
1,2022,7,1.0,Data Engineer,135000,100,US,M
2,2021,5,1.0,Data Analyst,100000,100,US,M
3,2021,5,0.5,Machine Learning,270000,100,US,L
4,2021,5,1.0,Data Engineer,26005,0,US,L

In [21]:
testeo.experience_level=testeo.experience_level.apply(lambda x: experience_level[x])

testeo.head()

,work_year,experience_level,employment_type,job_title,remote_ratio,company_location,company_size
0,2020,7,1.0,Machine Learning,0,JP,S
1,2020,5,1.0,Data Analyst,100,US,L
2,2020,5,1.0,Data Analyst,100,US,L
3,2020,5,1.0,Machine Learning,0,CN,M
4,2020,5,1.0,Data Analyst,100,IN,L

In [22]:
salary.work_year.unique()

array([2022, 2021, 2020])

In [23]:
salary.remote_ratio.unique()

array([100,   0,  50])

In [24]:
salary.company_location.value_counts()

US    296
GB     41
CA     25
DE     23
IN     19
FR     12
ES     12
GR     10
JP      4
NL      4
PT      4
LU      3
AE      3
AT      3
PL      3
PK      3
TR      3
CH      2
AU      2
BR      2
NG      2
SI      2
BE      2
MT      1
IR      1
DZ      1
HU      1
CZ      1
HN      1
RO      1
CL      1
EE      1
UA      1
NZ      1
DK      1
CN      1
KE      1
VN      1
MX      1
IE      1
AS      1
MD      1
SG      1
Name: company_location, dtype: int64

En la columna company_location nos quedamos solamente con los 10 primeros que son ma mayoria de paises

In [25]:
def company_location(x):
    if 'US' in x:
        return 'US'
    elif 'GB' in x:
        return 'GB'
    elif 'CA' in x:
        return 'CA'
    elif 'DE' in x:
        return 'DE'
    elif 'IN' in x:
        return 'IN'
    elif 'FR' in x:
        return 'FR'
    elif 'ES' in x:
        return 'ES'
    elif 'GR' in x:
        return 'GR'
    elif 'JP' in x:
        return 'JP'
    else:
        return 'Other'

In [26]:
salary.company_location=salary.company_location.apply(company_location)

In [27]:
testeo.company_location=testeo.company_location.apply(company_location)

In [28]:
salary.head()

,work_year,experience_level,employment_type,job_title,salary_in_usd,remote_ratio,company_location,company_size
0,2022,7,1.0,Data Engineer,140250,100,US,M
1,2022,7,1.0,Data Engineer,135000,100,US,M
2,2021,5,1.0,Data Analyst,100000,100,US,M
3,2021,5,0.5,Machine Learning,270000,100,US,L
4,2021,5,1.0,Data Engineer,26005,0,US,L

In [29]:
#from sklearn.preprocessing import StandardScaler

#scaler=StandardScaler()
#
#salary[['experience_level']]=scaler.fit_transform(salary[['experience_level']])

#salary.head()

In [30]:
#testeo[['experience_level']]=scaler.fit_transform(testeo[['experience_level']])

#testeo.head()

Utilizamos get_dummies

In [31]:
salary=pd.get_dummies(salary, columns=['experience_level','employment_type','work_year','remote_ratio','job_title','company_location','company_size'], drop_first=True)

salary.head()

,salary_in_usd,experience_level_5,experience_level_7,experience_level_10,employment_type_1.0,work_year_2021,work_year_2022,remote_ratio_50,remote_ratio_100,job_title_Data Engineer,...,company_location_ES,company_location_FR,company_location_GB,company_location_GR,company_location_IN,company_location_JP,company_location_Other,company_location_US,company_size_M,company_size_S
0,140250,0,1,0,1,0,1,0,1,1,...,0,0,0,0,0,0,0,1,1,0
1,135000,0,1,0,1,0,1,0,1,1,...,0,0,0,0,0,0,0,1,1,0
2,100000,1,0,0,1,1,0,0,1,0,...,0,0,0,0,0,0,0,1,1,0
3,270000,1,0,0,0,1,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0
4,26005,1,0,0,1,1,0,0,0,1,...,0,0,0,0,0,0,0,1,0,0

In [32]:
salary.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 23 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   salary_in_usd               500 non-null    int64
 1   experience_level_5          500 non-null    uint8
 2   experience_level_7          500 non-null    uint8
 3   experience_level_10         500 non-null    uint8
 4   employment_type_1.0         500 non-null    uint8
 5   work_year_2021              500 non-null    uint8
 6   work_year_2022              500 non-null    uint8
 7   remote_ratio_50             500 non-null    uint8
 8   remote_ratio_100            500 non-null    uint8
 9   job_title_Data Engineer     500 non-null    uint8
 10  job_title_Data Scientist    500 non-null    uint8
 11  job_title_Machine Learning  500 non-null    uint8
 12  company_location_DE         500 non-null    uint8
 13  company_location_ES         500 non-null    uint8
 14  company_location_FR         500 non-null    uint8
 15  company_location_GB         500 non-null    uint8
 16  company_location_GR         500 non-null    uint8
 17  company_location_IN         500 non-null    uint8
 18  company_location_JP         500 non-null    uint8
 19  company_location_Other      500 non-null    uint8
 20  company_location_US         500 non-null    uint8
 21  company_size_M              500 non-null    uint8
 22  company_size_S              500 non-null    uint8
dtypes: int64(1), uint8(22)
memory usage: 14.8 KB

In [33]:
testeo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 107 entries, 0 to 106
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   work_year         107 non-null    int64
 1   experience_level  107 non-null    int64
 2   employment_type   107 non-null    float64
 3   job_title         107 non-null    object
 4   remote_ratio      107 non-null    int64
 5   company_location  107 non-null    object
 6   company_size      107 non-null    object
dtypes: float64(1), int64(3), object(3)
memory usage: 6.0+ KB

In [34]:
testeo=pd.get_dummies(testeo, columns=['experience_level','employment_type','work_year','remote_ratio','job_title','company_location','company_size'], drop_first=True)

testeo.head()

,experience_level_5,experience_level_7,experience_level_10,employment_type_1.0,work_year_2021,work_year_2022,remote_ratio_50,remote_ratio_100,job_title_Data Engineer,job_title_Data Scientist,...,company_location_ES,company_location_FR,company_location_GB,company_location_GR,company_location_IN,company_location_JP,company_location_Other,company_location_US,company_size_M,company_size_S
0,0,1,0,1,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
1,1,0,0,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,1,0,0
2,1,0,0,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,1,0,0
3,1,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,1,0
4,1,0,0,1,0,0,0,1,0,0,...,0,0,0,0,1,0,0,0,0,0

In [35]:
salary_x=salary.drop('salary_in_usd', axis=1)
salary_y=salary.salary_in_usd

In [36]:
from sklearn.model_selection import train_test_split as tts

In [51]:
X_train, X_test, y_train, y_test = tts(salary_x, salary_y,train_size=0.9, test_size=0.1,random_state =71)

In [52]:
from sklearn.linear_model import LinearRegression as LinReg
from sklearn.linear_model import Lasso        # regularizacion L1
from sklearn.linear_model import Ridge        # regularizacion L2
from sklearn.linear_model import ElasticNet
from sklearn.svm import SVR
from sklearn.ensemble import RandomForestRegressor as RFR  
from sklearn.tree import ExtraTreeRegressor as ETR
from sklearn.ensemble import GradientBoostingRegressor as GBR
from xgboost import XGBRegressor as XGBR
from catboost import CatBoostRegressor as CTR

In [53]:
from lightgbm import LGBMRegressor as LGBMR

**Iniciamos los modelos**

In [54]:
linreg=LinReg()
lasso=Lasso()
ridge=Ridge()
elastic=ElasticNet()
svr=SVR()
rfr=RFR()
etr=ETR()
gbr=GBR()
xgbr=XGBR()
ctr=CTR()
lgbmr=LGBMR()

**Entrenamos modelos**

In [55]:
linreg.fit(X_train, y_train)
lasso.fit(X_train, y_train)
ridge.fit(X_train, y_train)
elastic.fit(X_train, y_train)
svr.fit(X_train, y_train)
rfr.fit(X_train, y_train)
etr.fit(X_train, y_train)
gbr.fit(X_train, y_train)
xgbr.fit(X_train, y_train)
ctr.fit(X_train, y_train)
lgbmr.fit(X_train, y_train)

Learning rate set to 0.03609
0:	learn: 69301.0734175	total: 1.51ms	remaining: 1.51s
1:	learn: 68462.7585238	total: 2.32ms	remaining: 1.16s
2:	learn: 67801.0406972	total: 2.55ms	remaining: 848ms
3:	learn: 66979.5548903	total: 3.2ms	remaining: 797ms
4:	learn: 66209.7701625	total: 3.88ms	remaining: 772ms
5:	learn: 65517.3043424	total: 4.67ms	remaining: 774ms
6:	learn: 64973.4096958	total: 5.36ms	remaining: 760ms
7:	learn: 64307.5734340	total: 6.18ms	remaining: 767ms
8:	learn: 63832.3107120	total: 6.37ms	remaining: 701ms
9:	learn: 63319.4101200	total: 6.67ms	remaining: 660ms
10:	learn: 62751.6251778	total: 7.36ms	remaining: 661ms
11:	learn: 62270.7582433	total: 7.7ms	remaining: 634ms
12:	learn: 61866.2255648	total: 8.34ms	remaining: 633ms
13:	learn: 61406.0489392	total: 9.05ms	remaining: 638ms
14:	learn: 60810.0906630	total: 9.87ms	remaining: 648ms
15:	learn: 60364.9522054	total: 10.7ms	remaining: 656ms
16:	learn: 59922.3647579	total: 11.4ms	remaining: 660ms
17:	learn: 59489.8594818	total: 12.1ms	remaining: 660ms
18:	learn: 59155.2191803	total: 12.4ms	remaining: 641ms
19:	learn: 58895.8001348	total: 12.7ms	remaining: 623ms
20:	learn: 58472.5298195	total: 13.3ms	remaining: 622ms
21:	learn: 58015.6957035	total: 14.1ms	remaining: 627ms
22:	learn: 57582.4572632	total: 14.7ms	remaining: 626ms
23:	learn: 57194.3797185	total: 15.4ms	remaining: 628ms
24:	learn: 56946.8535435	total: 16.1ms	remaining: 629ms
25:	learn: 56634.8653981	total: 16.9ms	remaining: 633ms
26:	learn: 56252.5508894	total: 17.6ms	remaining: 634ms
27:	learn: 55951.1621867	total: 18.2ms	remaining: 633ms
28:	learn: 55696.4348003	total: 19ms	remaining: 635ms
29:	learn: 55443.8278248	total: 19.7ms	remaining: 637ms
30:	learn: 55135.0908038	total: 20.4ms	remaining: 637ms
31:	learn: 54916.5469836	total: 21.2ms	remaining: 642ms
32:	learn: 54660.0074999	total: 21.9ms	remaining: 641ms
33:	learn: 54463.8745725	total: 22.6ms	remaining: 641ms
34:	learn: 54180.3097433	total: 23.3ms	remaining: 641ms
35:	learn: 53981.8067831	total: 23.9ms	remaining: 641ms
36:	learn: 53758.3540124	total: 24.7ms	remaining: 643ms
37:	learn: 53587.2610601	total: 25.5ms	remaining: 647ms
38:	learn: 53383.1549758	total: 26.3ms	remaining: 648ms
39:	learn: 53161.8628436	total: 27ms	remaining: 648ms
40:	learn: 53040.9144274	total: 27.8ms	remaining: 650ms
41:	learn: 52919.5436105	total: 28ms	remaining: 638ms
42:	learn: 52745.8382811	total: 28.7ms	remaining: 638ms
43:	learn: 52575.6201749	total: 29.4ms	remaining: 638ms
44:	learn: 52416.0926086	total: 30.2ms	remaining: 640ms
45:	learn: 52348.3755253	total: 30.3ms	remaining: 629ms
46:	learn: 52290.0006602	total: 30.5ms	remaining: 619ms
47:	learn: 52193.6457355	total: 31.2ms	remaining: 619ms
48:	learn: 52066.9349479	total: 31.9ms	remaining: 620ms
49:	learn: 51926.5586486	total: 32.6ms	remaining: 619ms
50:	learn: 51767.0345295	total: 33.3ms	remaining: 620ms
51:	learn: 51667.3111146	total: 34ms	remaining: 620ms
52:	learn: 51593.0649791	total: 34.3ms	remaining: 612ms
53:	learn: 51435.5777654	total: 34.9ms	remaining: 612ms
54:	learn: 51297.5985600	total: 35.7ms	remaining: 613ms
55:	learn: 51093.8604455	total: 36.5ms	remaining: 615ms
56:	learn: 50986.6458375	total: 37.8ms	remaining: 626ms
57:	learn: 50882.2659481	total: 38.6ms	remaining: 626ms
58:	learn: 50786.2254361	total: 39.4ms	remaining: 628ms
59:	learn: 50581.6623148	total: 40.1ms	remaining: 628ms
60:	learn: 50485.0917577	total: 40.9ms	remaining: 629ms
61:	learn: 50409.3030076	total: 41.3ms	remaining: 625ms
62:	learn: 50314.9035682	total: 42ms	remaining: 624ms
63:	learn: 50212.0829837	total: 42.8ms	remaining: 625ms
64:	learn: 50030.7328283	total: 43.4ms	remaining: 625ms
65:	learn: 49918.2681934	total: 44.2ms	remaining: 626ms
66:	learn: 49827.6384652	total: 44.9ms	remaining: 625ms
67:	learn: 49732.5679051	total: 45.6ms	remaining: 625ms
68:	learn: 49641.7187712	total: 46.3ms	remaining: 625ms
69:	learn: 49620.7339346	total: 46.7ms	remaining: 620ms
70:	learn: 49545.7797499	total: 47.4ms	remaining: 620ms
71:	learn: 49334.6582142	total: 48.2ms	remaining: 622ms
72:	learn: 49233.8372077	total: 48.9ms	remaining: 621ms
73:	learn: 49155.9225303	total: 49.7ms	remaining: 622ms
74:	learn: 49117.3698452	total: 50.4ms	remaining: 621ms
75:	learn: 48992.5821354	total: 51.1ms	remaining: 621ms
76:	learn: 48937.9526309	total: 51.8ms	remaining: 621ms
77:	learn: 48889.3642365	total: 52.6ms	remaining: 621ms
78:	learn: 48811.5435268	total: 53.4ms	remaining: 623ms
79:	learn: 48736.9228514	total: 54.1ms	remaining: 623ms
80:	learn: 48663.5589292	total: 54.9ms	remaining: 623ms
81:	learn: 48493.0956010	total: 55.6ms	remaining: 622ms
82:	learn: 48413.6399712	total: 56.3ms	remaining: 622ms
83:	learn: 48367.3538709	total: 57ms	remaining: 622ms
84:	learn: 48314.1545027	total: 57.7ms	remaining: 621ms
85:	learn: 48230.7730405	total: 58.4ms	remaining: 620ms
86:	learn: 48187.7016343	total: 59.2ms	remaining: 621ms
87:	learn: 48085.8694800	total: 60ms	remaining: 622ms
88:	learn: 48048.8491084	total: 60.5ms	remaining: 620ms
89:	learn: 47993.9050840	total: 61.2ms	remaining: 619ms
90:	learn: 47965.3372197	total: 61.6ms	remaining: 615ms
91:	learn: 47909.1800801	total: 62.3ms	remaining: 614ms
92:	learn: 47832.1711603	total: 63ms	remaining: 614ms
93:	learn: 47763.1747335	total: 63.7ms	remaining: 614ms
94:	learn: 47718.1379813	total: 64.4ms	remaining: 613ms
95:	learn: 47621.1099021	total: 65.1ms	remaining: 613ms
96:	learn: 47552.2242766	total: 65.7ms	remaining: 612ms
97:	learn: 47509.1425696	total: 66.5ms	remaining: 612ms
98:	learn: 47424.4332172	total: 67.1ms	remaining: 611ms
99:	learn: 47371.0039054	total: 67.9ms	remaining: 611ms
100:	learn: 47220.4411206	total: 68.6ms	remaining: 611ms
101:	learn: 47168.9158964	total: 69.3ms	remaining: 610ms
102:	learn: 47101.6678737	total: 70.1ms	remaining: 611ms
103:	learn: 47075.9808195	total: 70.4ms	remaining: 606ms
104:	learn: 47022.5113412	total: 71.1ms	remaining: 606ms
105:	learn: 46974.8944316	total: 71.8ms	remaining: 605ms
106:	learn: 46921.9817263	total: 72.6ms	remaining: 606ms
107:	learn: 46832.4849759	total: 73.3ms	remaining: 605ms
108:	learn: 46753.7550945	total: 74ms	remaining: 605ms
109:	learn: 46718.4720946	total: 74.6ms	remaining: 604ms
110:	learn: 46677.1771137	total: 75.4ms	remaining: 604ms
111:	learn: 46551.4489792	total: 76.2ms	remaining: 604ms
112:	learn: 46489.8985158	total: 76.9ms	remaining: 604ms
113:	learn: 46469.2372311	total: 77.6ms	remaining: 603ms
114:	learn: 46438.1628394	total: 78.4ms	remaining: 603ms
115:	learn: 46353.9615819	total: 79ms	remaining: 602ms
116:	learn: 46283.6752992	total: 79.8ms	remaining: 602ms
117:	learn: 46219.4087569	total: 80.5ms	remaining: 602ms
118:	learn: 46205.9356478	total: 80.8ms	remaining: 599ms
119:	learn: 46150.1690808	total: 81.7ms	remaining: 599ms
120:	learn: 46099.6397698	total: 82.3ms	remaining: 598ms
121:	learn: 46053.4662431	total: 83.1ms	remaining: 598ms
122:	learn: 46011.5810725	total: 84ms	remaining: 599ms
123:	learn: 45970.5685131	total: 84.7ms	remaining: 598ms
124:	learn: 45885.6219603	total: 85.5ms	remaining: 598ms
125:	learn: 45875.1169708	total: 85.8ms	remaining: 595ms
126:	learn: 45851.3739152	total: 86.5ms	remaining: 595ms
127:	learn: 45777.4171661	total: 87.1ms	remaining: 594ms
128:	learn: 45760.4489769	total: 87.9ms	remaining: 593ms
129:	learn: 45706.4981869	total: 88.5ms	remaining: 592ms
130:	learn: 45668.6873629	total: 89.2ms	remaining: 592ms
131:	learn: 45636.8835522	total: 89.9ms	remaining: 591ms
132:	learn: 45572.8599411	total: 90.6ms	remaining: 590ms
133:	learn: 45534.3413047	total: 91.3ms	remaining: 590ms
134:	learn: 45461.2853566	total: 92.1ms	remaining: 590ms
135:	learn: 45414.5560492	total: 92.8ms	remaining: 589ms
136:	learn: 45298.6852534	total: 93.5ms	remaining: 589ms
137:	learn: 45292.1088948	total: 93.7ms	remaining: 585ms
138:	learn: 45274.6013854	total: 94.4ms	remaining: 585ms
139:	learn: 45232.7550536	total: 95.1ms	remaining: 584ms
140:	learn: 45191.0361540	total: 95.8ms	remaining: 583ms
141:	learn: 45108.6786713	total: 96.4ms	remaining: 583ms
142:	learn: 45073.6979050	total: 97.1ms	remaining: 582ms
143:	learn: 45005.9751798	total: 98ms	remaining: 582ms
144:	learn: 44979.2940832	total: 98.4ms	remaining: 580ms
145:	learn: 44906.5368419	total: 99.1ms	remaining: 580ms
146:	learn: 44897.2359142	total: 99.4ms	remaining: 577ms
147:	learn: 44892.7935942	total: 99.6ms	remaining: 573ms
148:	learn: 44842.5617860	total: 100ms	remaining: 574ms
149:	learn: 44814.6218932	total: 101ms	remaining: 573ms
150:	learn: 44807.5369704	total: 101ms	remaining: 570ms
151:	learn: 44782.1089488	total: 102ms	remaining: 570ms
152:	learn: 44759.8326871	total: 103ms	remaining: 570ms
153:	learn: 44723.8630368	total: 104ms	remaining: 569ms
154:	learn: 44675.8563216	total: 104ms	remaining: 568ms
155:	learn: 44653.1740294	total: 105ms	remaining: 568ms
156:	learn: 44628.1539379	total: 106ms	remaining: 568ms
157:	learn: 44566.3264734	total: 106ms	remaining: 567ms
158:	learn: 44525.8722106	total: 107ms	remaining: 567ms
159:	learn: 44483.3912802	total: 108ms	remaining: 566ms
160:	learn: 44454.2548797	total: 109ms	remaining: 566ms
161:	learn: 44435.3398381	total: 109ms	remaining: 565ms
162:	learn: 44393.7876624	total: 110ms	remaining: 564ms
163:	learn: 44332.3449058	total: 111ms	remaining: 564ms
164:	learn: 44273.6940825	total: 111ms	remaining: 563ms
165:	learn: 44258.9458919	total: 112ms	remaining: 563ms
166:	learn: 44195.8247161	total: 113ms	remaining: 563ms
167:	learn: 44149.2085846	total: 113ms	remaining: 562ms
168:	learn: 44066.4810528	total: 114ms	remaining: 562ms
169:	learn: 44043.5284411	total: 115ms	remaining: 561ms
170:	learn: 43971.9828687	total: 116ms	remaining: 561ms
171:	learn: 43955.5076717	total: 116ms	remaining: 560ms
172:	learn: 43933.2798561	total: 117ms	remaining: 560ms
173:	learn: 43900.4082648	total: 118ms	remaining: 559ms
174:	learn: 43862.6338389	total: 119ms	remaining: 559ms
175:	learn: 43830.4346487	total: 119ms	remaining: 559ms
176:	learn: 43816.2352565	total: 120ms	remaining: 558ms
177:	learn: 43802.7105982	total: 121ms	remaining: 558ms
178:	learn: 43797.8621598	total: 121ms	remaining: 555ms
179:	learn: 43757.6600554	total: 122ms	remaining: 555ms
180:	learn: 43682.6245466	total: 122ms	remaining: 554ms
181:	learn: 43650.7976233	total: 123ms	remaining: 554ms
182:	learn: 43637.0780870	total: 124ms	remaining: 553ms
183:	learn: 43563.3970560	total: 125ms	remaining: 553ms
184:	learn: 43548.0884575	total: 126ms	remaining: 553ms
185:	learn: 43485.6501225	total: 126ms	remaining: 553ms
186:	learn: 43413.4692298	total: 127ms	remaining: 553ms
187:	learn: 43396.0193194	total: 128ms	remaining: 552ms
188:	learn: 43374.5517590	total: 129ms	remaining: 551ms
189:	learn: 43360.9541223	total: 129ms	remaining: 551ms
190:	learn: 43309.1074625	total: 130ms	remaining: 550ms
191:	learn: 43296.4802479	total: 131ms	remaining: 550ms
192:	learn: 43257.1445977	total: 131ms	remaining: 549ms
193:	learn: 43222.2119765	total: 132ms	remaining: 549ms
194:	learn: 43183.2279948	total: 133ms	remaining: 548ms
195:	learn: 43147.6881006	total: 134ms	remaining: 548ms
196:	learn: 43126.4944963	total: 134ms	remaining: 548ms
197:	learn: 43070.9190610	total: 135ms	remaining: 548ms
198:	learn: 43002.2470609	total: 136ms	remaining: 547ms
199:	learn: 42963.2882929	total: 137ms	remaining: 547ms
200:	learn: 42950.2365014	total: 137ms	remaining: 546ms
201:	learn: 42934.6508410	total: 138ms	remaining: 545ms
202:	learn: 42919.2750886	total: 139ms	remaining: 545ms
203:	learn: 42863.1129918	total: 140ms	remaining: 544ms
204:	learn: 42842.1597315	total: 140ms	remaining: 544ms
205:	learn: 42822.4418524	total: 141ms	remaining: 543ms
206:	learn: 42769.9717599	total: 142ms	remaining: 543ms
207:	learn: 42707.7458974	total: 142ms	remaining: 542ms
208:	learn: 42691.7657700	total: 143ms	remaining: 542ms
209:	learn: 42654.4975530	total: 144ms	remaining: 542ms
210:	learn: 42620.1666816	total: 145ms	remaining: 542ms
211:	learn: 42587.8140341	total: 146ms	remaining: 541ms
212:	learn: 42584.1624860	total: 146ms	remaining: 538ms
213:	learn: 42556.8194959	total: 146ms	remaining: 538ms
214:	learn: 42464.2623533	total: 147ms	remaining: 537ms
215:	learn: 42426.9765310	total: 148ms	remaining: 537ms
216:	learn: 42401.3408445	total: 149ms	remaining: 536ms
217:	learn: 42383.8622873	total: 149ms	remaining: 536ms
218:	learn: 42360.3648783	total: 150ms	remaining: 535ms
219:	learn: 42343.2932763	total: 151ms	remaining: 535ms
220:	learn: 42307.7393373	total: 152ms	remaining: 534ms
221:	learn: 42277.0578034	total: 152ms	remaining: 534ms
222:	learn: 42240.6240204	total: 153ms	remaining: 533ms
223:	learn: 42226.6676235	total: 154ms	remaining: 532ms
224:	learn: 42204.7128361	total: 154ms	remaining: 532ms
225:	learn: 42190.6762833	total: 155ms	remaining: 531ms
226:	learn: 42144.3442226	total: 156ms	remaining: 530ms
227:	learn: 42114.1370037	total: 156ms	remaining: 530ms
228:	learn: 42099.3569863	total: 157ms	remaining: 529ms
229:	learn: 42077.0935907	total: 158ms	remaining: 529ms
230:	learn: 42054.3088740	total: 159ms	remaining: 528ms
231:	learn: 42037.0859249	total: 159ms	remaining: 528ms
232:	learn: 42011.2134972	total: 160ms	remaining: 528ms
233:	learn: 42002.3909371	total: 161ms	remaining: 527ms
234:	learn: 41975.6102697	total: 162ms	remaining: 526ms
235:	learn: 41960.8837836	total: 162ms	remaining: 526ms
236:	learn: 41937.4675566	total: 163ms	remaining: 525ms
237:	learn: 41897.7105032	total: 164ms	remaining: 525ms
238:	learn: 41883.4457650	total: 165ms	remaining: 525ms
239:	learn: 41869.7182086	total: 165ms	remaining: 524ms
240:	learn: 41837.8230780	total: 166ms	remaining: 523ms
241:	learn: 41807.8196963	total: 167ms	remaining: 523ms
242:	learn: 41751.3770834	total: 168ms	remaining: 522ms
243:	learn: 41729.7197835	total: 168ms	remaining: 522ms
244:	learn: 41721.8845992	total: 169ms	remaining: 521ms
245:	learn: 41661.3632490	total: 170ms	remaining: 521ms
246:	learn: 41640.1793435	total: 171ms	remaining: 520ms
247:	learn: 41621.3516668	total: 171ms	remaining: 519ms
248:	learn: 41594.6769344	total: 172ms	remaining: 519ms
249:	learn: 41574.2702722	total: 173ms	remaining: 518ms
250:	learn: 41557.7538250	total: 173ms	remaining: 518ms
251:	learn: 41549.8933782	total: 174ms	remaining: 517ms
252:	learn: 41538.3261673	total: 175ms	remaining: 516ms
253:	learn: 41526.0897021	total: 176ms	remaining: 516ms
254:	learn: 41474.3828929	total: 176ms	remaining: 515ms
255:	learn: 41463.8997627	total: 177ms	remaining: 515ms
256:	learn: 41437.5033091	total: 178ms	remaining: 514ms
257:	learn: 41425.0732211	total: 179ms	remaining: 514ms
258:	learn: 41391.1409538	total: 179ms	remaining: 513ms
259:	learn: 41363.9162758	total: 180ms	remaining: 512ms
260:	learn: 41337.9864417	total: 181ms	remaining: 512ms
261:	learn: 41326.2963143	total: 181ms	remaining: 511ms
262:	learn: 41296.5273787	total: 182ms	remaining: 510ms
263:	learn: 41272.7118676	total: 183ms	remaining: 510ms
264:	learn: 41249.8353077	total: 184ms	remaining: 509ms
265:	learn: 41208.8111091	total: 184ms	remaining: 509ms
266:	learn: 41175.6981312	total: 185ms	remaining: 508ms
267:	learn: 41166.9856254	total: 186ms	remaining: 507ms
268:	learn: 41129.3617312	total: 186ms	remaining: 507ms
269:	learn: 41113.4847482	total: 187ms	remaining: 506ms
270:	learn: 41102.7823227	total: 188ms	remaining: 506ms
271:	learn: 41076.4990815	total: 189ms	remaining: 505ms
272:	learn: 41048.5140700	total: 189ms	remaining: 504ms
273:	learn: 41018.5191499	total: 190ms	remaining: 504ms

274:	learn: 40994.3143369	total: 191ms	remaining: 504ms
275:	learn: 40939.9884167	total: 192ms	remaining: 503ms
276:	learn: 40916.7440010	total: 193ms	remaining: 503ms
277:	learn: 40891.3596720	total: 193ms	remaining: 502ms
278:	learn: 40858.3738447	total: 194ms	remaining: 502ms
279:	learn: 40821.8215337	total: 195ms	remaining: 501ms
280:	learn: 40791.9336001	total: 195ms	remaining: 500ms
281:	learn: 40777.4579688	total: 196ms	remaining: 499ms
282:	learn: 40759.3469552	total: 197ms	remaining: 498ms
283:	learn: 40750.5561009	total: 197ms	remaining: 498ms
284:	learn: 40734.6408199	total: 198ms	remaining: 497ms
285:	learn: 40711.5780506	total: 199ms	remaining: 496ms
286:	learn: 40667.8076609	total: 199ms	remaining: 496ms
287:	learn: 40648.8191968	total: 200ms	remaining: 495ms
288:	learn: 40635.7397321	total: 201ms	remaining: 494ms
289:	learn: 40610.0855870	total: 201ms	remaining: 493ms
290:	learn: 40589.0329916	total: 202ms	remaining: 492ms
291:	learn: 40572.4237442	total: 203ms	remaining: 492ms
292:	learn: 40572.0305572	total: 203ms	remaining: 490ms
293:	learn: 40547.2016253	total: 204ms	remaining: 490ms
294:	learn: 40513.5571291	total: 205ms	remaining: 489ms
295:	learn: 40501.9884926	total: 205ms	remaining: 488ms
296:	learn: 40489.2284690	total: 206ms	remaining: 488ms
297:	learn: 40466.3181404	total: 207ms	remaining: 487ms
298:	learn: 40433.8384603	total: 207ms	remaining: 486ms
299:	learn: 40418.4227611	total: 208ms	remaining: 486ms
300:	learn: 40407.7672026	total: 209ms	remaining: 485ms
301:	learn: 40396.5690393	total: 210ms	remaining: 484ms
302:	learn: 40354.4531618	total: 210ms	remaining: 484ms
303:	learn: 40331.1411173	total: 211ms	remaining: 483ms
304:	learn: 40282.0389692	total: 212ms	remaining: 482ms
305:	learn: 40258.9547646	total: 212ms	remaining: 481ms
306:	learn: 40237.2536435	total: 213ms	remaining: 481ms
307:	learn: 40227.0752129	total: 214ms	remaining: 480ms
308:	learn: 40206.1480340	total: 214ms	remaining: 479ms
309:	learn: 40182.9598637	total: 215ms	remaining: 478ms
310:	learn: 40171.2770946	total: 216ms	remaining: 478ms
311:	learn: 40160.8990292	total: 216ms	remaining: 477ms
312:	learn: 40138.7219235	total: 217ms	remaining: 477ms
313:	learn: 40102.4285331	total: 218ms	remaining: 476ms
314:	learn: 40084.1176175	total: 219ms	remaining: 475ms
315:	learn: 40056.4762438	total: 219ms	remaining: 475ms
316:	learn: 40008.9115181	total: 220ms	remaining: 474ms
317:	learn: 39988.1439360	total: 221ms	remaining: 474ms
318:	learn: 39978.3597481	total: 221ms	remaining: 473ms
319:	learn: 39969.0131062	total: 222ms	remaining: 472ms
320:	learn: 39947.6597532	total: 223ms	remaining: 471ms
321:	learn: 39928.9080918	total: 224ms	remaining: 471ms
322:	learn: 39919.5548621	total: 224ms	remaining: 470ms
323:	learn: 39912.0962028	total: 225ms	remaining: 470ms
324:	learn: 39901.6266983	total: 226ms	remaining: 469ms
325:	learn: 39878.7964704	total: 227ms	remaining: 468ms
326:	learn: 39842.9576429	total: 227ms	remaining: 468ms
327:	learn: 39836.0165490	total: 228ms	remaining: 467ms
328:	learn: 39826.7780516	total: 229ms	remaining: 466ms
329:	learn: 39797.3722544	total: 229ms	remaining: 466ms
330:	learn: 39790.7969911	total: 230ms	remaining: 465ms
331:	learn: 39755.8423770	total: 231ms	remaining: 464ms
332:	learn: 39755.5676663	total: 231ms	remaining: 463ms
333:	learn: 39733.4934796	total: 232ms	remaining: 462ms
334:	learn: 39728.3115978	total: 232ms	remaining: 461ms
335:	learn: 39719.1669227	total: 233ms	remaining: 460ms
336:	learn: 39685.3887949	total: 234ms	remaining: 460ms
337:	learn: 39676.5334669	total: 234ms	remaining: 459ms
338:	learn: 39657.3934819	total: 235ms	remaining: 458ms
339:	learn: 39652.1213181	total: 236ms	remaining: 458ms
340:	learn: 39632.3325544	total: 236ms	remaining: 457ms
341:	learn: 39622.5627458	total: 237ms	remaining: 456ms
342:	learn: 39614.9364412	total: 238ms	remaining: 456ms
343:	learn: 39586.4158328	total: 239ms	remaining: 455ms
344:	learn: 39560.0438460	total: 239ms	remaining: 454ms
345:	learn: 39554.7550091	total: 240ms	remaining: 454ms
346:	learn: 39540.4322446	total: 241ms	remaining: 453ms
347:	learn: 39519.8548155	total: 242ms	remaining: 453ms
348:	learn: 39503.9500970	total: 242ms	remaining: 452ms
349:	learn: 39487.4327341	total: 243ms	remaining: 451ms
350:	learn: 39474.5795370	total: 244ms	remaining: 450ms
351:	learn: 39468.7747456	total: 244ms	remaining: 450ms
352:	learn: 39450.6680436	total: 245ms	remaining: 449ms
353:	learn: 39427.5977396	total: 246ms	remaining: 449ms
354:	learn: 39418.4655418	total: 246ms	remaining: 448ms
355:	learn: 39411.7196922	total: 247ms	remaining: 447ms
356:	learn: 39405.4824610	total: 248ms	remaining: 447ms
357:	learn: 39405.2330985	total: 248ms	remaining: 445ms
358:	learn: 39396.6118734	total: 249ms	remaining: 444ms
359:	learn: 39388.2891115	total: 249ms	remaining: 443ms
360:	learn: 39382.7440063	total: 250ms	remaining: 443ms
361:	learn: 39370.7684506	total: 251ms	remaining: 442ms
362:	learn: 39366.4913339	total: 252ms	remaining: 441ms
363:	learn: 39363.0817853	total: 253ms	remaining: 442ms
364:	learn: 39331.3473853	total: 254ms	remaining: 441ms
365:	learn: 39302.8586869	total: 254ms	remaining: 441ms
366:	learn: 39246.3978326	total: 255ms	remaining: 440ms
367:	learn: 39233.6789589	total: 256ms	remaining: 439ms
368:	learn: 39226.5782783	total: 256ms	remaining: 438ms
369:	learn: 39209.9094546	total: 257ms	remaining: 438ms
370:	learn: 39200.0557952	total: 258ms	remaining: 437ms
371:	learn: 39195.7893944	total: 259ms	remaining: 436ms
372:	learn: 39181.2862541	total: 259ms	remaining: 436ms
373:	learn: 39137.6627109	total: 260ms	remaining: 435ms
374:	learn: 39124.2159861	total: 261ms	remaining: 435ms
375:	learn: 39083.2322023	total: 262ms	remaining: 434ms
376:	learn: 39078.5550016	total: 262ms	remaining: 433ms
377:	learn: 39076.4347801	total: 263ms	remaining: 433ms
378:	learn: 39055.9413000	total: 264ms	remaining: 432ms
379:	learn: 39033.5229896	total: 264ms	remaining: 431ms
380:	learn: 38996.8975941	total: 265ms	remaining: 431ms
381:	learn: 38987.0396162	total: 266ms	remaining: 430ms
382:	learn: 38981.5622506	total: 266ms	remaining: 429ms
383:	learn: 38964.6699568	total: 267ms	remaining: 428ms
384:	learn: 38953.8223353	total: 268ms	remaining: 428ms
385:	learn: 38947.6360954	total: 268ms	remaining: 427ms
386:	learn: 38941.7759857	total: 269ms	remaining: 426ms
387:	learn: 38938.3831437	total: 270ms	remaining: 426ms
388:	learn: 38923.3759276	total: 270ms	remaining: 425ms
389:	learn: 38915.5149242	total: 271ms	remaining: 424ms
390:	learn: 38893.4278760	total: 272ms	remaining: 423ms
391:	learn: 38891.1117658	total: 273ms	remaining: 423ms
392:	learn: 38873.7627211	total: 273ms	remaining: 422ms
393:	learn: 38860.7433960	total: 274ms	remaining: 421ms
394:	learn: 38854.7484983	total: 275ms	remaining: 421ms
395:	learn: 38829.4649825	total: 275ms	remaining: 420ms
396:	learn: 38826.4055150	total: 276ms	remaining: 419ms
397:	learn: 38814.1060825	total: 277ms	remaining: 419ms
398:	learn: 38802.4504695	total: 277ms	remaining: 418ms
399:	learn: 38764.0096273	total: 278ms	remaining: 417ms
400:	learn: 38760.2684811	total: 279ms	remaining: 417ms
401:	learn: 38753.2818965	total: 279ms	remaining: 416ms
402:	learn: 38738.1607982	total: 280ms	remaining: 415ms
403:	learn: 38724.2655533	total: 281ms	remaining: 414ms
404:	learn: 38711.8040207	total: 282ms	remaining: 414ms
405:	learn: 38703.7251111	total: 282ms	remaining: 413ms
406:	learn: 38682.3880289	total: 283ms	remaining: 412ms
407:	learn: 38661.4514451	total: 284ms	remaining: 412ms
408:	learn: 38659.3993632	total: 284ms	remaining: 411ms
409:	learn: 38639.8222966	total: 285ms	remaining: 410ms
410:	learn: 38626.2897141	total: 286ms	remaining: 409ms
411:	learn: 38619.4370788	total: 286ms	remaining: 409ms
412:	learn: 38581.7176785	total: 287ms	remaining: 408ms
413:	learn: 38567.5523597	total: 288ms	remaining: 407ms
414:	learn: 38555.5004633	total: 289ms	remaining: 407ms
415:	learn: 38537.5401363	total: 289ms	remaining: 406ms
416:	learn: 38516.4473706	total: 290ms	remaining: 405ms
417:	learn: 38493.9983983	total: 291ms	remaining: 405ms
418:	learn: 38483.4212242	total: 291ms	remaining: 404ms
419:	learn: 38447.4842905	total: 292ms	remaining: 403ms
420:	learn: 38440.6303793	total: 293ms	remaining: 403ms
421:	learn: 38433.1788687	total: 293ms	remaining: 402ms
422:	learn: 38421.0681789	total: 294ms	remaining: 401ms
423:	learn: 38410.1382047	total: 295ms	remaining: 401ms
424:	learn: 38403.3973379	total: 296ms	remaining: 400ms
425:	learn: 38403.2965717	total: 296ms	remaining: 399ms
426:	learn: 38398.2169748	total: 297ms	remaining: 398ms
427:	learn: 38387.2240178	total: 297ms	remaining: 397ms
428:	learn: 38380.3577799	total: 298ms	remaining: 396ms
429:	learn: 38361.2282776	total: 299ms	remaining: 396ms
430:	learn: 38348.7242335	total: 299ms	remaining: 395ms
431:	learn: 38314.8275765	total: 300ms	remaining: 394ms
432:	learn: 38290.3157622	total: 301ms	remaining: 394ms
433:	learn: 38287.4824659	total: 301ms	remaining: 393ms
434:	learn: 38254.1119755	total: 302ms	remaining: 392ms
435:	learn: 38241.9601141	total: 303ms	remaining: 392ms
436:	learn: 38235.6060705	total: 304ms	remaining: 391ms
437:	learn: 38230.6546444	total: 304ms	remaining: 390ms
438:	learn: 38216.7890432	total: 305ms	remaining: 390ms
439:	learn: 38203.9393595	total: 306ms	remaining: 389ms
440:	learn: 38188.9237071	total: 306ms	remaining: 388ms
441:	learn: 38157.2450692	total: 307ms	remaining: 388ms
442:	learn: 38147.0909854	total: 308ms	remaining: 387ms
443:	learn: 38141.2073314	total: 308ms	remaining: 386ms
444:	learn: 38130.4377378	total: 309ms	remaining: 386ms
445:	learn: 38117.9445623	total: 310ms	remaining: 385ms
446:	learn: 38094.3276522	total: 311ms	remaining: 384ms
447:	learn: 38084.0606070	total: 311ms	remaining: 384ms
448:	learn: 38073.5693862	total: 312ms	remaining: 383ms
449:	learn: 38053.7242001	total: 313ms	remaining: 382ms
450:	learn: 38045.0886426	total: 313ms	remaining: 382ms
451:	learn: 38036.0510185	total: 314ms	remaining: 381ms
452:	learn: 38009.1876820	total: 315ms	remaining: 380ms
453:	learn: 38002.1336319	total: 316ms	remaining: 379ms
454:	learn: 37991.3335483	total: 316ms	remaining: 379ms
455:	learn: 37974.6543419	total: 317ms	remaining: 378ms
456:	learn: 37940.2858273	total: 318ms	remaining: 377ms
457:	learn: 37926.1931120	total: 318ms	remaining: 377ms
458:	learn: 37915.3751080	total: 319ms	remaining: 376ms
459:	learn: 37905.3320637	total: 320ms	remaining: 375ms
460:	learn: 37887.2989034	total: 320ms	remaining: 375ms
461:	learn: 37875.0703575	total: 321ms	remaining: 374ms
462:	learn: 37867.6766388	total: 322ms	remaining: 373ms
463:	learn: 37865.8354793	total: 322ms	remaining: 372ms
464:	learn: 37840.2945542	total: 323ms	remaining: 372ms
465:	learn: 37815.9838664	total: 324ms	remaining: 371ms
466:	learn: 37797.1265319	total: 325ms	remaining: 370ms
467:	learn: 37787.5418388	total: 325ms	remaining: 370ms
468:	learn: 37762.3154260	total: 326ms	remaining: 369ms
469:	learn: 37758.4001393	total: 327ms	remaining: 369ms
470:	learn: 37751.8948909	total: 327ms	remaining: 368ms
471:	learn: 37745.8423828	total: 328ms	remaining: 367ms
472:	learn: 37741.7270391	total: 329ms	remaining: 366ms
473:	learn: 37731.1267277	total: 330ms	remaining: 366ms
474:	learn: 37698.7152143	total: 330ms	remaining: 365ms
475:	learn: 37676.5689223	total: 331ms	remaining: 364ms
476:	learn: 37667.4756863	total: 332ms	remaining: 364ms
477:	learn: 37657.6930925	total: 332ms	remaining: 363ms
478:	learn: 37640.9986016	total: 333ms	remaining: 362ms
479:	learn: 37635.3059691	total: 334ms	remaining: 361ms
480:	learn: 37629.6320975	total: 334ms	remaining: 361ms
481:	learn: 37613.9190179	total: 335ms	remaining: 360ms
482:	learn: 37607.8227268	total: 336ms	remaining: 359ms
483:	learn: 37604.6330543	total: 336ms	remaining: 359ms
484:	learn: 37593.6776616	total: 337ms	remaining: 358ms
485:	learn: 37576.2323784	total: 338ms	remaining: 357ms
486:	learn: 37571.7827829	total: 339ms	remaining: 357ms
487:	learn: 37564.5340200	total: 339ms	remaining: 356ms
488:	learn: 37555.9042272	total: 340ms	remaining: 355ms
489:	learn: 37536.3795738	total: 341ms	remaining: 355ms
490:	learn: 37527.6883319	total: 342ms	remaining: 354ms
491:	learn: 37519.5872601	total: 342ms	remaining: 353ms
492:	learn: 37514.7295298	total: 343ms	remaining: 353ms
493:	learn: 37504.5766662	total: 344ms	remaining: 352ms
494:	learn: 37488.0758824	total: 344ms	remaining: 351ms
495:	learn: 37465.1752335	total: 345ms	remaining: 351ms
496:	learn: 37452.6188076	total: 346ms	remaining: 350ms
497:	learn: 37446.9756360	total: 346ms	remaining: 349ms
498:	learn: 37423.5070101	total: 347ms	remaining: 348ms
499:	learn: 37398.6809571	total: 348ms	remaining: 348ms
500:	learn: 37393.2240096	total: 348ms	remaining: 347ms
501:	learn: 37391.3328621	total: 349ms	remaining: 346ms
502:	learn: 37386.6609561	total: 350ms	remaining: 346ms
503:	learn: 37386.5932488	total: 350ms	remaining: 344ms
504:	learn: 37381.4811895	total: 351ms	remaining: 344ms
505:	learn: 37357.7628878	total: 351ms	remaining: 343ms
506:	learn: 37348.3140356	total: 352ms	remaining: 342ms
507:	learn: 37329.4033536	total: 353ms	remaining: 342ms
508:	learn: 37321.1455160	total: 353ms	remaining: 341ms
509:	learn: 37314.1899437	total: 354ms	remaining: 340ms
510:	learn: 37305.9016037	total: 355ms	remaining: 340ms
511:	learn: 37286.8613478	total: 356ms	remaining: 339ms
512:	learn: 37276.6315530	total: 356ms	remaining: 338ms
513:	learn: 37271.7933606	total: 357ms	remaining: 338ms
514:	learn: 37267.1872324	total: 358ms	remaining: 337ms
515:	learn: 37249.3132873	total: 358ms	remaining: 336ms
516:	learn: 37240.7889238	total: 359ms	remaining: 335ms
517:	learn: 37223.1652400	total: 360ms	remaining: 335ms
518:	learn: 37216.8553405	total: 360ms	remaining: 334ms
519:	learn: 37201.5144594	total: 361ms	remaining: 333ms
520:	learn: 37198.2653428	total: 362ms	remaining: 333ms
521:	learn: 37194.9525558	total: 363ms	remaining: 332ms
522:	learn: 37187.3296914	total: 363ms	remaining: 331ms
523:	learn: 37173.5986246	total: 364ms	remaining: 331ms
524:	learn: 37149.7479128	total: 365ms	remaining: 330ms
525:	learn: 37145.2547355	total: 365ms	remaining: 329ms
526:	learn: 37143.0860172	total: 366ms	remaining: 329ms
527:	learn: 37122.6379394	total: 367ms	remaining: 328ms
528:	learn: 37117.9822637	total: 368ms	remaining: 327ms
529:	learn: 37116.2136201	total: 368ms	remaining: 327ms
530:	learn: 37110.6235453	total: 369ms	remaining: 326ms
531:	learn: 37071.4483445	total: 370ms	remaining: 325ms
532:	learn: 37067.9205042	total: 370ms	remaining: 324ms
533:	learn: 37060.8282198	total: 371ms	remaining: 324ms
534:	learn: 37058.3890059	total: 372ms	remaining: 323ms
535:	learn: 37048.8683745	total: 372ms	remaining: 322ms
536:	learn: 37034.0420919	total: 373ms	remaining: 322ms
537:	learn: 37025.6805782	total: 374ms	remaining: 321ms
538:	learn: 37004.4678748	total: 374ms	remaining: 320ms
539:	learn: 36995.4080229	total: 375ms	remaining: 320ms
540:	learn: 36969.2526818	total: 376ms	remaining: 319ms
541:	learn: 36949.4952117	total: 376ms	remaining: 318ms
542:	learn: 36946.4647018	total: 377ms	remaining: 317ms
543:	learn: 36927.0014070	total: 378ms	remaining: 317ms
544:	learn: 36911.3737269	total: 379ms	remaining: 316ms
545:	learn: 36895.7687343	total: 379ms	remaining: 315ms
546:	learn: 36866.5834548	total: 380ms	remaining: 315ms
547:	learn: 36859.9370607	total: 381ms	remaining: 314ms
548:	learn: 36859.0647465	total: 381ms	remaining: 313ms
549:	learn: 36858.3003214	total: 382ms	remaining: 313ms

550:	learn: 36838.9489531	total: 383ms	remaining: 312ms
551:	learn: 36814.3574166	total: 384ms	remaining: 311ms
552:	learn: 36809.8439061	total: 384ms	remaining: 311ms
553:	learn: 36802.1291488	total: 385ms	remaining: 310ms
554:	learn: 36792.0356181	total: 386ms	remaining: 310ms
555:	learn: 36779.8461220	total: 387ms	remaining: 309ms
556:	learn: 36767.4075014	total: 388ms	remaining: 308ms
557:	learn: 36757.4178147	total: 388ms	remaining: 308ms
558:	learn: 36753.5625723	total: 389ms	remaining: 307ms
559:	learn: 36728.7496433	total: 390ms	remaining: 306ms
560:	learn: 36691.1798604	total: 390ms	remaining: 305ms
561:	learn: 36684.1500481	total: 391ms	remaining: 305ms
562:	learn: 36667.4678021	total: 392ms	remaining: 304ms
563:	learn: 36665.8699494	total: 392ms	remaining: 303ms
564:	learn: 36640.2335713	total: 393ms	remaining: 303ms
565:	learn: 36615.6496814	total: 394ms	remaining: 302ms
566:	learn: 36592.0189390	total: 395ms	remaining: 301ms
567:	learn: 36585.1519372	total: 395ms	remaining: 301ms
568:	learn: 36564.4103060	total: 396ms	remaining: 300ms
569:	learn: 36562.8055865	total: 397ms	remaining: 299ms
570:	learn: 36555.1086991	total: 398ms	remaining: 299ms
571:	learn: 36537.2686962	total: 398ms	remaining: 298ms
572:	learn: 36512.7275167	total: 399ms	remaining: 297ms
573:	learn: 36511.0698409	total: 400ms	remaining: 297ms
574:	learn: 36506.2387236	total: 400ms	remaining: 296ms
575:	learn: 36501.3574275	total: 401ms	remaining: 295ms
576:	learn: 36489.0904577	total: 402ms	remaining: 295ms
577:	learn: 36481.8397450	total: 403ms	remaining: 294ms
578:	learn: 36463.8827351	total: 403ms	remaining: 293ms
579:	learn: 36456.3572029	total: 404ms	remaining: 293ms
580:	learn: 36439.2602904	total: 405ms	remaining: 292ms
581:	learn: 36430.8480926	total: 405ms	remaining: 291ms
582:	learn: 36413.0483199	total: 406ms	remaining: 290ms
583:	learn: 36408.3659341	total: 407ms	remaining: 290ms
584:	learn: 36397.3364230	total: 407ms	remaining: 289ms
585:	learn: 36385.5260111	total: 408ms	remaining: 288ms
586:	learn: 36384.2862271	total: 409ms	remaining: 288ms
587:	learn: 36360.9644459	total: 410ms	remaining: 287ms
588:	learn: 36355.2092151	total: 410ms	remaining: 286ms
589:	learn: 36351.1371852	total: 411ms	remaining: 286ms
590:	learn: 36337.6884496	total: 412ms	remaining: 285ms
591:	learn: 36333.8036451	total: 412ms	remaining: 284ms
592:	learn: 36311.3594008	total: 413ms	remaining: 284ms
593:	learn: 36292.9565558	total: 414ms	remaining: 283ms
594:	learn: 36285.5717713	total: 414ms	remaining: 282ms
595:	learn: 36271.4818878	total: 415ms	remaining: 281ms
596:	learn: 36254.6888156	total: 416ms	remaining: 281ms
597:	learn: 36252.8324059	total: 417ms	remaining: 280ms
598:	learn: 36240.5212318	total: 417ms	remaining: 279ms
599:	learn: 36237.8274402	total: 418ms	remaining: 279ms
600:	learn: 36235.6193162	total: 419ms	remaining: 278ms
601:	learn: 36226.1245420	total: 420ms	remaining: 277ms
602:	learn: 36222.8469394	total: 420ms	remaining: 277ms
603:	learn: 36209.9210900	total: 421ms	remaining: 276ms
604:	learn: 36200.3190707	total: 422ms	remaining: 275ms
605:	learn: 36181.9887115	total: 422ms	remaining: 275ms
606:	learn: 36172.2849281	total: 423ms	remaining: 274ms
607:	learn: 36165.7336315	total: 424ms	remaining: 273ms
608:	learn: 36157.0340502	total: 424ms	remaining: 272ms
609:	learn: 36140.6143704	total: 425ms	remaining: 272ms
610:	learn: 36138.1585195	total: 426ms	remaining: 271ms
611:	learn: 36117.1954291	total: 427ms	remaining: 270ms
612:	learn: 36090.6650718	total: 427ms	remaining: 270ms
613:	learn: 36069.0501840	total: 428ms	remaining: 269ms
614:	learn: 36052.6972221	total: 429ms	remaining: 268ms
615:	learn: 36050.2890473	total: 429ms	remaining: 268ms
616:	learn: 36039.7869651	total: 430ms	remaining: 267ms
617:	learn: 36033.5897941	total: 431ms	remaining: 266ms
618:	learn: 36031.1456296	total: 432ms	remaining: 266ms
619:	learn: 36029.7421714	total: 432ms	remaining: 265ms
620:	learn: 36010.6788209	total: 433ms	remaining: 264ms
621:	learn: 36008.5221652	total: 434ms	remaining: 263ms
622:	learn: 36007.7893894	total: 434ms	remaining: 263ms
623:	learn: 35975.5819455	total: 435ms	remaining: 262ms
624:	learn: 35942.2927897	total: 436ms	remaining: 261ms
625:	learn: 35936.5034452	total: 436ms	remaining: 261ms
626:	learn: 35925.4775515	total: 437ms	remaining: 260ms
627:	learn: 35918.4041833	total: 438ms	remaining: 259ms
628:	learn: 35912.1496959	total: 439ms	remaining: 259ms
629:	learn: 35908.4941330	total: 439ms	remaining: 258ms
630:	learn: 35895.9261553	total: 440ms	remaining: 257ms
631:	learn: 35876.3876591	total: 441ms	remaining: 257ms
632:	learn: 35871.2351673	total: 441ms	remaining: 256ms
633:	learn: 35867.4916439	total: 442ms	remaining: 255ms
634:	learn: 35861.6626241	total: 443ms	remaining: 255ms
635:	learn: 35841.1380194	total: 444ms	remaining: 254ms
636:	learn: 35834.3758610	total: 444ms	remaining: 253ms
637:	learn: 35832.9161902	total: 445ms	remaining: 252ms
638:	learn: 35827.2583936	total: 446ms	remaining: 252ms
639:	learn: 35817.7298291	total: 446ms	remaining: 251ms
640:	learn: 35815.6243907	total: 447ms	remaining: 250ms
641:	learn: 35809.9477770	total: 448ms	remaining: 250ms
642:	learn: 35800.7542806	total: 448ms	remaining: 249ms
643:	learn: 35784.8270178	total: 449ms	remaining: 248ms
644:	learn: 35779.3723268	total: 450ms	remaining: 248ms
645:	learn: 35771.9783711	total: 450ms	remaining: 247ms
646:	learn: 35752.9493755	total: 451ms	remaining: 246ms
647:	learn: 35742.8204125	total: 452ms	remaining: 245ms
648:	learn: 35736.3943490	total: 453ms	remaining: 245ms
649:	learn: 35721.8459368	total: 453ms	remaining: 244ms
650:	learn: 35705.8787692	total: 454ms	remaining: 243ms
651:	learn: 35691.1940469	total: 455ms	remaining: 243ms
652:	learn: 35680.5288578	total: 455ms	remaining: 242ms
653:	learn: 35674.8182546	total: 456ms	remaining: 241ms
654:	learn: 35654.2840668	total: 457ms	remaining: 241ms
655:	learn: 35625.0003754	total: 457ms	remaining: 240ms
656:	learn: 35618.5559861	total: 458ms	remaining: 239ms
657:	learn: 35612.6045003	total: 459ms	remaining: 238ms
658:	learn: 35606.1869385	total: 460ms	remaining: 238ms
659:	learn: 35604.9488402	total: 460ms	remaining: 237ms
660:	learn: 35599.1476779	total: 461ms	remaining: 236ms
661:	learn: 35579.2981946	total: 462ms	remaining: 236ms
662:	learn: 35576.5739628	total: 462ms	remaining: 235ms
663:	learn: 35562.3081901	total: 463ms	remaining: 234ms
664:	learn: 35561.5651493	total: 464ms	remaining: 234ms
665:	learn: 35554.7384739	total: 464ms	remaining: 233ms
666:	learn: 35543.9882064	total: 465ms	remaining: 232ms
667:	learn: 35538.5932818	total: 466ms	remaining: 231ms
668:	learn: 35534.4746466	total: 466ms	remaining: 231ms
669:	learn: 35528.4306407	total: 467ms	remaining: 230ms
670:	learn: 35514.0031018	total: 468ms	remaining: 229ms
671:	learn: 35498.8006048	total: 469ms	remaining: 229ms
672:	learn: 35492.6383109	total: 469ms	remaining: 228ms
673:	learn: 35484.8402202	total: 470ms	remaining: 227ms
674:	learn: 35472.0751009	total: 471ms	remaining: 227ms
675:	learn: 35466.6874432	total: 471ms	remaining: 226ms
676:	learn: 35449.8335810	total: 472ms	remaining: 225ms
677:	learn: 35437.2120642	total: 473ms	remaining: 225ms
678:	learn: 35429.6246408	total: 474ms	remaining: 224ms
679:	learn: 35422.8877395	total: 474ms	remaining: 223ms
680:	learn: 35416.9321896	total: 475ms	remaining: 223ms
681:	learn: 35409.3837510	total: 476ms	remaining: 222ms
682:	learn: 35404.2744227	total: 476ms	remaining: 221ms
683:	learn: 35392.9695483	total: 477ms	remaining: 220ms
684:	learn: 35387.9296934	total: 478ms	remaining: 220ms
685:	learn: 35371.9507706	total: 479ms	remaining: 219ms
686:	learn: 35364.0216554	total: 479ms	remaining: 218ms
687:	learn: 35352.9946840	total: 480ms	remaining: 218ms
688:	learn: 35348.3674155	total: 481ms	remaining: 217ms
689:	learn: 35341.4629921	total: 481ms	remaining: 216ms
690:	learn: 35300.7017456	total: 482ms	remaining: 216ms
691:	learn: 35298.3093483	total: 483ms	remaining: 215ms
692:	learn: 35288.0309459	total: 483ms	remaining: 214ms
693:	learn: 35281.4262805	total: 484ms	remaining: 213ms
694:	learn: 35276.8642494	total: 485ms	remaining: 213ms
695:	learn: 35273.1835777	total: 485ms	remaining: 212ms
696:	learn: 35267.5561640	total: 486ms	remaining: 211ms
697:	learn: 35264.8742779	total: 487ms	remaining: 211ms
698:	learn: 35262.7078068	total: 487ms	remaining: 210ms
699:	learn: 35244.2464579	total: 488ms	remaining: 209ms
700:	learn: 35228.6058875	total: 489ms	remaining: 209ms
701:	learn: 35223.8804111	total: 490ms	remaining: 208ms
702:	learn: 35219.8814514	total: 490ms	remaining: 207ms
703:	learn: 35213.5546346	total: 491ms	remaining: 206ms
704:	learn: 35212.6920806	total: 492ms	remaining: 206ms
705:	learn: 35196.2687604	total: 492ms	remaining: 205ms
706:	learn: 35188.6625424	total: 493ms	remaining: 204ms
707:	learn: 35184.0149127	total: 494ms	remaining: 204ms
708:	learn: 35177.8622893	total: 494ms	remaining: 203ms
709:	learn: 35173.4661934	total: 495ms	remaining: 202ms
710:	learn: 35166.5179970	total: 496ms	remaining: 202ms
711:	learn: 35164.8730019	total: 497ms	remaining: 201ms
712:	learn: 35162.5722989	total: 497ms	remaining: 200ms
713:	learn: 35160.5329133	total: 498ms	remaining: 199ms
714:	learn: 35147.5082850	total: 499ms	remaining: 199ms
715:	learn: 35141.7642022	total: 499ms	remaining: 198ms
716:	learn: 35137.4991564	total: 500ms	remaining: 197ms
717:	learn: 35126.1226296	total: 501ms	remaining: 197ms
718:	learn: 35115.9291943	total: 502ms	remaining: 196ms
719:	learn: 35113.3865888	total: 502ms	remaining: 195ms
720:	learn: 35096.5791042	total: 503ms	remaining: 195ms
721:	learn: 35088.1615845	total: 504ms	remaining: 194ms
722:	learn: 35085.1884539	total: 504ms	remaining: 193ms
723:	learn: 35079.3066749	total: 505ms	remaining: 193ms
724:	learn: 35071.5089931	total: 506ms	remaining: 192ms
725:	learn: 35068.3855693	total: 506ms	remaining: 191ms
726:	learn: 35058.7787967	total: 507ms	remaining: 190ms
727:	learn: 35056.6590516	total: 508ms	remaining: 190ms
728:	learn: 35053.4118557	total: 509ms	remaining: 189ms
729:	learn: 35047.4865994	total: 509ms	remaining: 188ms
730:	learn: 35044.3875295	total: 510ms	remaining: 188ms
731:	learn: 35031.8062054	total: 511ms	remaining: 187ms
732:	learn: 35024.0846477	total: 511ms	remaining: 186ms
733:	learn: 35019.4852919	total: 512ms	remaining: 186ms
734:	learn: 35014.3602117	total: 513ms	remaining: 185ms
735:	learn: 35008.2099235	total: 514ms	remaining: 184ms
736:	learn: 35004.6828739	total: 514ms	remaining: 183ms
737:	learn: 34999.1704395	total: 515ms	remaining: 183ms
738:	learn: 34994.8144040	total: 516ms	remaining: 182ms
739:	learn: 34988.5715561	total: 516ms	remaining: 181ms
740:	learn: 34980.6718008	total: 517ms	remaining: 181ms
741:	learn: 34969.5169752	total: 518ms	remaining: 180ms
742:	learn: 34964.1432998	total: 518ms	remaining: 179ms
743:	learn: 34961.8504040	total: 519ms	remaining: 179ms
744:	learn: 34955.5219083	total: 520ms	remaining: 178ms
745:	learn: 34954.7165315	total: 520ms	remaining: 177ms
746:	learn: 34949.5632743	total: 521ms	remaining: 177ms
747:	learn: 34946.2332415	total: 522ms	remaining: 176ms
748:	learn: 34929.9912560	total: 523ms	remaining: 175ms
749:	learn: 34917.0104533	total: 523ms	remaining: 174ms
750:	learn: 34903.1591011	total: 524ms	remaining: 174ms
751:	learn: 34897.6556736	total: 525ms	remaining: 173ms
752:	learn: 34884.9853695	total: 526ms	remaining: 172ms
753:	learn: 34880.2173063	total: 526ms	remaining: 172ms
754:	learn: 34877.3810409	total: 527ms	remaining: 171ms
755:	learn: 34874.6544662	total: 528ms	remaining: 170ms
756:	learn: 34873.0638541	total: 528ms	remaining: 170ms
757:	learn: 34872.5331404	total: 529ms	remaining: 169ms
758:	learn: 34857.1111335	total: 530ms	remaining: 168ms
759:	learn: 34851.6478633	total: 531ms	remaining: 168ms
760:	learn: 34847.4487547	total: 531ms	remaining: 167ms
761:	learn: 34838.3581263	total: 532ms	remaining: 166ms
762:	learn: 34832.1901206	total: 533ms	remaining: 165ms
763:	learn: 34807.9746091	total: 533ms	remaining: 165ms
764:	learn: 34805.4300030	total: 534ms	remaining: 164ms
765:	learn: 34790.5998473	total: 535ms	remaining: 163ms
766:	learn: 34786.1792783	total: 536ms	remaining: 163ms
767:	learn: 34785.5196104	total: 536ms	remaining: 162ms
768:	learn: 34781.4914670	total: 537ms	remaining: 161ms
769:	learn: 34768.0331405	total: 538ms	remaining: 161ms
770:	learn: 34766.3441495	total: 538ms	remaining: 160ms
771:	learn: 34765.4232093	total: 539ms	remaining: 159ms
772:	learn: 34761.3997359	total: 540ms	remaining: 159ms
773:	learn: 34755.4992025	total: 541ms	remaining: 158ms
774:	learn: 34749.3487901	total: 541ms	remaining: 157ms
775:	learn: 34735.4908642	total: 542ms	remaining: 156ms
776:	learn: 34726.2474169	total: 543ms	remaining: 156ms
777:	learn: 34719.9090752	total: 543ms	remaining: 155ms
778:	learn: 34714.9231589	total: 544ms	remaining: 154ms
779:	learn: 34712.6461573	total: 545ms	remaining: 154ms
780:	learn: 34697.3460784	total: 545ms	remaining: 153ms
781:	learn: 34692.4554052	total: 546ms	remaining: 152ms
782:	learn: 34689.2563395	total: 547ms	remaining: 152ms
783:	learn: 34686.2156982	total: 548ms	remaining: 151ms
784:	learn: 34681.6729467	total: 548ms	remaining: 150ms
785:	learn: 34671.3582955	total: 549ms	remaining: 149ms
786:	learn: 34661.1482257	total: 550ms	remaining: 149ms
787:	learn: 34655.2038419	total: 550ms	remaining: 148ms
788:	learn: 34645.4305359	total: 551ms	remaining: 147ms
789:	learn: 34643.7275082	total: 552ms	remaining: 147ms
790:	learn: 34641.8386682	total: 552ms	remaining: 146ms
791:	learn: 34638.0609174	total: 553ms	remaining: 145ms
792:	learn: 34631.5609708	total: 554ms	remaining: 145ms
793:	learn: 34627.2008338	total: 555ms	remaining: 144ms
794:	learn: 34622.2267525	total: 555ms	remaining: 143ms
795:	learn: 34616.2908239	total: 556ms	remaining: 142ms
796:	learn: 34613.6649916	total: 557ms	remaining: 142ms
797:	learn: 34610.0711747	total: 557ms	remaining: 141ms
798:	learn: 34609.5256389	total: 558ms	remaining: 140ms
799:	learn: 34606.2329372	total: 559ms	remaining: 140ms
800:	learn: 34588.4496808	total: 560ms	remaining: 139ms
801:	learn: 34576.4680962	total: 560ms	remaining: 138ms
802:	learn: 34571.8674932	total: 561ms	remaining: 138ms
803:	learn: 34567.2983439	total: 562ms	remaining: 137ms
804:	learn: 34562.5208355	total: 562ms	remaining: 136ms
805:	learn: 34560.1380740	total: 563ms	remaining: 136ms
806:	learn: 34552.5775247	total: 564ms	remaining: 135ms
807:	learn: 34551.2692327	total: 564ms	remaining: 134ms
808:	learn: 34547.1012027	total: 565ms	remaining: 133ms
809:	learn: 34546.5984659	total: 566ms	remaining: 133ms
810:	learn: 34546.2307103	total: 567ms	remaining: 132ms
811:	learn: 34534.3014126	total: 567ms	remaining: 131ms
812:	learn: 34528.6792163	total: 568ms	remaining: 131ms
813:	learn: 34518.9489088	total: 569ms	remaining: 130ms
814:	learn: 34514.0136477	total: 569ms	remaining: 129ms
815:	learn: 34507.0834460	total: 570ms	remaining: 129ms
816:	learn: 34499.6503060	total: 571ms	remaining: 128ms
817:	learn: 34496.1788778	total: 571ms	remaining: 127ms
818:	learn: 34492.1158580	total: 572ms	remaining: 126ms
819:	learn: 34486.7645052	total: 573ms	remaining: 126ms
820:	learn: 34482.4191794	total: 573ms	remaining: 125ms

821:	learn: 34479.9588449	total: 574ms	remaining: 124ms
822:	learn: 34474.8213443	total: 575ms	remaining: 124ms
823:	learn: 34472.6395434	total: 576ms	remaining: 123ms
824:	learn: 34472.1727270	total: 576ms	remaining: 122ms
825:	learn: 34468.9447309	total: 577ms	remaining: 122ms
826:	learn: 34466.4128282	total: 578ms	remaining: 121ms
827:	learn: 34455.8259559	total: 579ms	remaining: 120ms
828:	learn: 34453.0421638	total: 579ms	remaining: 119ms
829:	learn: 34451.4291126	total: 580ms	remaining: 119ms
830:	learn: 34443.3994198	total: 581ms	remaining: 118ms
831:	learn: 34438.6781910	total: 581ms	remaining: 117ms
832:	learn: 34432.0338230	total: 582ms	remaining: 117ms
833:	learn: 34429.3324491	total: 583ms	remaining: 116ms
834:	learn: 34416.7202234	total: 584ms	remaining: 115ms
835:	learn: 34415.0434687	total: 584ms	remaining: 115ms
836:	learn: 34412.9751976	total: 585ms	remaining: 114ms
837:	learn: 34409.7276317	total: 586ms	remaining: 113ms
838:	learn: 34397.3384112	total: 586ms	remaining: 113ms
839:	learn: 34388.9718051	total: 587ms	remaining: 112ms
840:	learn: 34384.8689490	total: 588ms	remaining: 111ms
841:	learn: 34379.7829832	total: 589ms	remaining: 110ms
842:	learn: 34377.9668488	total: 589ms	remaining: 110ms
843:	learn: 34364.4275763	total: 590ms	remaining: 109ms
844:	learn: 34361.4987141	total: 591ms	remaining: 108ms
845:	learn: 34348.9680811	total: 591ms	remaining: 108ms
846:	learn: 34342.7304681	total: 592ms	remaining: 107ms
847:	learn: 34335.9539597	total: 593ms	remaining: 106ms
848:	learn: 34329.3106473	total: 594ms	remaining: 106ms
849:	learn: 34327.8177004	total: 594ms	remaining: 105ms
850:	learn: 34326.4260861	total: 595ms	remaining: 104ms
851:	learn: 34319.6244036	total: 596ms	remaining: 103ms
852:	learn: 34311.7126448	total: 596ms	remaining: 103ms
853:	learn: 34302.0865415	total: 597ms	remaining: 102ms
854:	learn: 34297.3777970	total: 598ms	remaining: 101ms
855:	learn: 34287.2382962	total: 598ms	remaining: 101ms
856:	learn: 34285.4141858	total: 599ms	remaining: 100ms
857:	learn: 34273.2983919	total: 600ms	remaining: 99.3ms
858:	learn: 34269.9106967	total: 601ms	remaining: 98.6ms
859:	learn: 34267.4616818	total: 602ms	remaining: 97.9ms
860:	learn: 34261.6344077	total: 602ms	remaining: 97.3ms
861:	learn: 34258.5072363	total: 603ms	remaining: 96.6ms
862:	learn: 34251.1337703	total: 604ms	remaining: 95.9ms
863:	learn: 34239.3052115	total: 605ms	remaining: 95.2ms
864:	learn: 34225.1569491	total: 605ms	remaining: 94.5ms
865:	learn: 34217.1484181	total: 606ms	remaining: 93.8ms
866:	learn: 34208.6025529	total: 607ms	remaining: 93.1ms
867:	learn: 34206.8629860	total: 608ms	remaining: 92.4ms
868:	learn: 34201.1594349	total: 608ms	remaining: 91.7ms
869:	learn: 34189.6111932	total: 609ms	remaining: 91ms
870:	learn: 34186.2498399	total: 610ms	remaining: 90.3ms
871:	learn: 34176.9831815	total: 610ms	remaining: 89.6ms
872:	learn: 34170.6542307	total: 611ms	remaining: 88.9ms
873:	learn: 34162.6126989	total: 612ms	remaining: 88.2ms
874:	learn: 34155.9608097	total: 612ms	remaining: 87.5ms
875:	learn: 34153.4116522	total: 613ms	remaining: 86.8ms
876:	learn: 34137.4336198	total: 614ms	remaining: 86.1ms
877:	learn: 34133.5966284	total: 615ms	remaining: 85.4ms
878:	learn: 34127.8168203	total: 615ms	remaining: 84.7ms
879:	learn: 34120.5393358	total: 616ms	remaining: 84ms
880:	learn: 34116.0631132	total: 617ms	remaining: 83.3ms
881:	learn: 34098.3336280	total: 617ms	remaining: 82.6ms
882:	learn: 34088.8017679	total: 618ms	remaining: 81.9ms
883:	learn: 34080.6845776	total: 619ms	remaining: 81.2ms
884:	learn: 34068.5068043	total: 619ms	remaining: 80.5ms
885:	learn: 34060.0475764	total: 620ms	remaining: 79.8ms
886:	learn: 34046.0725913	total: 621ms	remaining: 79.1ms
887:	learn: 34034.6609836	total: 621ms	remaining: 78.4ms
888:	learn: 34028.2880551	total: 622ms	remaining: 77.7ms
889:	learn: 34026.6946210	total: 623ms	remaining: 77ms
890:	learn: 34024.1859447	total: 624ms	remaining: 76.3ms
891:	learn: 34013.2918362	total: 624ms	remaining: 75.6ms
892:	learn: 34002.3969027	total: 625ms	remaining: 74.9ms
893:	learn: 33999.0651723	total: 626ms	remaining: 74.2ms
894:	learn: 33986.0011832	total: 627ms	remaining: 73.5ms
895:	learn: 33985.1129944	total: 627ms	remaining: 72.8ms
896:	learn: 33981.5447124	total: 628ms	remaining: 72.1ms
897:	learn: 33979.4266177	total: 629ms	remaining: 71.4ms
898:	learn: 33966.3133960	total: 629ms	remaining: 70.7ms
899:	learn: 33962.4209720	total: 630ms	remaining: 70ms
900:	learn: 33954.8473176	total: 631ms	remaining: 69.3ms
901:	learn: 33950.1659753	total: 631ms	remaining: 68.6ms
902:	learn: 33943.1340974	total: 632ms	remaining: 67.9ms
903:	learn: 33939.9700509	total: 633ms	remaining: 67.2ms
904:	learn: 33932.2973263	total: 633ms	remaining: 66.5ms
905:	learn: 33927.0968215	total: 634ms	remaining: 65.8ms
906:	learn: 33919.2339843	total: 635ms	remaining: 65.1ms
907:	learn: 33914.4331664	total: 636ms	remaining: 64.4ms
908:	learn: 33911.4508349	total: 636ms	remaining: 63.7ms
909:	learn: 33904.6733864	total: 637ms	remaining: 63ms
910:	learn: 33897.1215751	total: 638ms	remaining: 62.3ms
911:	learn: 33893.3512645	total: 638ms	remaining: 61.6ms
912:	learn: 33884.9205288	total: 639ms	remaining: 60.9ms
913:	learn: 33879.7325779	total: 640ms	remaining: 60.2ms
914:	learn: 33872.5237649	total: 640ms	remaining: 59.5ms
915:	learn: 33861.1021912	total: 641ms	remaining: 58.8ms
916:	learn: 33850.1989007	total: 642ms	remaining: 58.1ms
917:	learn: 33846.1567006	total: 642ms	remaining: 57.4ms
918:	learn: 33840.3415533	total: 643ms	remaining: 56.7ms
919:	learn: 33833.3215892	total: 644ms	remaining: 56ms
920:	learn: 33823.5814066	total: 645ms	remaining: 55.3ms
921:	learn: 33820.9081262	total: 645ms	remaining: 54.6ms
922:	learn: 33807.7468253	total: 646ms	remaining: 53.9ms
923:	learn: 33803.3671227	total: 647ms	remaining: 53.2ms
924:	learn: 33798.0647550	total: 648ms	remaining: 52.5ms
925:	learn: 33797.3043277	total: 648ms	remaining: 51.8ms
926:	learn: 33787.7780876	total: 649ms	remaining: 51.1ms
927:	learn: 33779.4651045	total: 650ms	remaining: 50.4ms
928:	learn: 33772.5529034	total: 651ms	remaining: 49.7ms
929:	learn: 33770.4054107	total: 651ms	remaining: 49ms
930:	learn: 33760.6453470	total: 652ms	remaining: 48.3ms
931:	learn: 33759.4186126	total: 653ms	remaining: 47.6ms
932:	learn: 33755.2595269	total: 653ms	remaining: 46.9ms
933:	learn: 33752.4580669	total: 654ms	remaining: 46.2ms
934:	learn: 33750.1953159	total: 655ms	remaining: 45.5ms
935:	learn: 33746.6072920	total: 655ms	remaining: 44.8ms
936:	learn: 33744.2855379	total: 656ms	remaining: 44.1ms
937:	learn: 33738.1500603	total: 657ms	remaining: 43.4ms
938:	learn: 33724.8669634	total: 657ms	remaining: 42.7ms
939:	learn: 33719.6820286	total: 658ms	remaining: 42ms
940:	learn: 33715.7613551	total: 659ms	remaining: 41.3ms
941:	learn: 33706.9993967	total: 660ms	remaining: 40.6ms
942:	learn: 33698.5746209	total: 660ms	remaining: 39.9ms
943:	learn: 33697.1623727	total: 661ms	remaining: 39.2ms
944:	learn: 33688.9660960	total: 662ms	remaining: 38.5ms
945:	learn: 33681.0047659	total: 662ms	remaining: 37.8ms
946:	learn: 33671.9523418	total: 663ms	remaining: 37.1ms
947:	learn: 33665.8836788	total: 664ms	remaining: 36.4ms
948:	learn: 33665.3219861	total: 664ms	remaining: 35.7ms
949:	learn: 33663.9713531	total: 665ms	remaining: 35ms
950:	learn: 33654.1774704	total: 666ms	remaining: 34.3ms
951:	learn: 33650.2268159	total: 667ms	remaining: 33.6ms
952:	learn: 33648.1606088	total: 667ms	remaining: 32.9ms
953:	learn: 33644.6078861	total: 668ms	remaining: 32.2ms
954:	learn: 33641.1247147	total: 669ms	remaining: 31.5ms
955:	learn: 33634.2761890	total: 669ms	remaining: 30.8ms
956:	learn: 33629.2983004	total: 670ms	remaining: 30.1ms
957:	learn: 33619.3137707	total: 671ms	remaining: 29.4ms
958:	learn: 33615.0207787	total: 672ms	remaining: 28.7ms
959:	learn: 33614.1096436	total: 672ms	remaining: 28ms
960:	learn: 33611.0417369	total: 673ms	remaining: 27.3ms
961:	learn: 33608.4288679	total: 674ms	remaining: 26.6ms
962:	learn: 33607.7350497	total: 674ms	remaining: 25.9ms
963:	learn: 33604.3006893	total: 675ms	remaining: 25.2ms
964:	learn: 33592.4184564	total: 676ms	remaining: 24.5ms
965:	learn: 33589.3938091	total: 677ms	remaining: 23.8ms
966:	learn: 33587.6694372	total: 677ms	remaining: 23.1ms
967:	learn: 33577.9055159	total: 678ms	remaining: 22.4ms
968:	learn: 33577.4601437	total: 679ms	remaining: 21.7ms
969:	learn: 33572.4049940	total: 679ms	remaining: 21ms
970:	learn: 33566.6568419	total: 680ms	remaining: 20.3ms
971:	learn: 33549.7249964	total: 681ms	remaining: 19.6ms
972:	learn: 33547.4064588	total: 682ms	remaining: 18.9ms
973:	learn: 33535.6073407	total: 682ms	remaining: 18.2ms
974:	learn: 33532.8176398	total: 683ms	remaining: 17.5ms
975:	learn: 33528.8319343	total: 684ms	remaining: 16.8ms
976:	learn: 33525.3375397	total: 684ms	remaining: 16.1ms
977:	learn: 33520.0492881	total: 685ms	remaining: 15.4ms
978:	learn: 33516.4171195	total: 686ms	remaining: 14.7ms
979:	learn: 33514.2918834	total: 686ms	remaining: 14ms
980:	learn: 33512.6516206	total: 687ms	remaining: 13.3ms
981:	learn: 33510.1298150	total: 688ms	remaining: 12.6ms
982:	learn: 33500.4794757	total: 688ms	remaining: 11.9ms
983:	learn: 33498.3514290	total: 689ms	remaining: 11.2ms
984:	learn: 33495.4362029	total: 690ms	remaining: 10.5ms
985:	learn: 33494.0074116	total: 691ms	remaining: 9.8ms
986:	learn: 33491.3094309	total: 691ms	remaining: 9.11ms
987:	learn: 33489.9715995	total: 692ms	remaining: 8.4ms
988:	learn: 33484.4341195	total: 693ms	remaining: 7.7ms
989:	learn: 33478.9547075	total: 693ms	remaining: 7ms
990:	learn: 33469.6628931	total: 694ms	remaining: 6.3ms
991:	learn: 33466.4181120	total: 695ms	remaining: 5.6ms
992:	learn: 33466.0364892	total: 696ms	remaining: 4.9ms
993:	learn: 33460.7558178	total: 696ms	remaining: 4.2ms
994:	learn: 33458.4721981	total: 697ms	remaining: 3.5ms
995:	learn: 33454.7544331	total: 698ms	remaining: 2.8ms
996:	learn: 33449.7068230	total: 698ms	remaining: 2.1ms
997:	learn: 33445.9889397	total: 699ms	remaining: 1.4ms
998:	learn: 33443.7801163	total: 700ms	remaining: 700us
999:	learn: 33442.1045765	total: 700ms	remaining: 0us

LGBMRegressor()

In [42]:
from sklearn.metrics import mean_squared_error as mse

In [43]:
from sklearn.metrics import r2_score as r2

In [44]:
from sklearn.linear_model import PoissonRegressor as PR

In [45]:
pr=PR()

In [46]:
pr.fit(X_train, y_train)

PoissonRegressor()

**Prediccion y Evaluación**

In [58]:

y_pred=pr.predict(X_test)

mse(y_test, y_pred, squared=False), r2(y_test, y_pred)

(34385.75143561772, 0.7016775506869151)

In [59]:
# regresion lineal

y_pred=linreg.predict(X_test)

mse(y_test, y_pred, squared=False), r2(y_test, y_pred)

(41535.03754681895, 0.5647306249183817)

In [60]:
linreg.score(X_train, y_train), linreg.score(X_test, y_test)

(0.4908365143161678, 0.5647306249183817)

In [61]:
# lasso

y_pred=lasso.predict(X_test)

mse(y_test, y_pred, squared=False) , r2(y_test, y_pred)

(41533.01531110086, 0.5647730082121738)

In [62]:
lasso.score(X_train, y_train), lasso.score(X_test, y_test)

(0.49083628063506823, 0.5647730082121738)

In [63]:
# ridge

y_pred=ridge.predict(X_test)

mse(y_test, y_pred, squared=False), r2(y_test, y_pred)

(41477.85334646364, 0.5659283316427279)

In [64]:
ridge.score(X_train, y_train), ridge.score(X_test, y_test)

(0.48996537142775864, 0.5659283316427279)

In [65]:
# elastic

y_pred=elastic.predict(X_test)

mse(y_test, y_pred, squared=False), r2(y_test, y_pred)

(53665.384518830906, 0.2733632009067194)

In [66]:
elastic.score(X_train, y_train), elastic.score(X_test, y_test)

(0.25234145471580793, 0.2733632009067194)

In [67]:
# svr

y_pred=svr.predict(X_test)

mse(y_test, y_pred, squared=False) , r2(y_test, y_pred) # RMSE

(63074.834895864056, -0.003786017773553363)

In [68]:
svr.score(X_train, y_train), svr.score(X_test, y_test)

(-0.020640913480909573, -0.003786017773553363)

In [69]:
# rfr

y_pred=rfr.predict(X_test)

mse(y_test, y_pred, squared=False)  , r2(y_test, y_pred)# RMSE

(44261.70985474292, 0.5057060771339514)

In [70]:
rfr.score(X_train, y_train), rfr.score(X_test, y_test)

(0.7779803048257296, 0.5057060771339514)

In [71]:
# etr

y_pred=etr.predict(X_test)

mse(y_test, y_pred, squared=False) , r2(y_test, y_pred) # RMSE

(82211.97656868151, -0.7052932644650938)

In [72]:
etr.score(X_train, y_train), etr.score(X_test, y_test)

(0.8214066404562996, -0.7052932644650938)

In [73]:
#gbr
y_pred=gbr.predict(X_test)

mse(y_test, y_pred, squared=False) , r2(y_test, y_pred)

(37214.45105726091, 0.6505764823169562)

In [74]:
gbr.score(X_train, y_train), gbr.score(X_test, y_test)

(0.58884395071537, 0.6505764823169562)

In [75]:
#xgbr

y_pred=xgbr.predict(X_test)

mse(y_test, y_pred, squared=False), r2(y_test, y_pred)  # RMSE

(50210.925948517215, 0.36390005530861325)

In [76]:
xgbr.score(X_train, y_train), xgbr.score(X_test, y_test)

(0.8167227763473948, 0.36390005530861325)

In [77]:
#ctr
y_pred=ctr.predict(X_test)

mse(y_test, y_pred, squared=False), r2(y_test, y_pred)  # RMSE

(44378.306947505786, 0.5030984442528541)

In [78]:
ctr.score(X_train, y_train), ctr.score(X_test, y_test)

(0.7731322792557785, 0.5030984442528541)

In [79]:
y_pred=lgbmr.predict(X_test)

mse(y_test, y_pred, squared=False), r2(y_test, y_pred)  # RMSE

(49053.34307783245, 0.39289177237156125)

In [80]:
lgbmr.score(X_train, y_train), lgbmr.score(X_test, y_test)

(0.5741775231141739, 0.39289177237156125)

In [56]:
#Import Lazypredict and all libraries
import lazypredict
from lazypredict.Supervised import LazyRegressor
from sklearn.model_selection import train_test_split
import os
import pandas as pd
import numpy as np

In [57]:
lazy = LazyRegressor(verbose=0,ignore_warnings=True, custom_metric=None)
models, predictions = lazy.fit(X_train, X_test, y_train, y_test)

100%|███████████████████████████████████████████| 42/42 [00:02<00:00, 20.93it/s]

In [50]:
print(models)

                               Adjusted R-Squared  R-Squared      RMSE  \
Model
OrthogonalMatchingPursuitCV                  0.27       0.44  50128.21
LassoLarsCV                                  0.23       0.40  51681.32
LassoCV                                      0.23       0.40  51747.07
HuberRegressor                               0.23       0.40  51764.42
LarsCV                                       0.22       0.39  52083.48
BayesianRidge                                0.21       0.38  52396.89
LassoLarsIC                                  0.21       0.38  52451.38
RidgeCV                                      0.20       0.38  52616.03
LassoLars                                    0.19       0.37  52852.07
Ridge                                        0.19       0.37  52865.70
SGDRegressor                                 0.19       0.37  52867.40
PassiveAggressiveRegressor                   0.19       0.37  52872.75
Lasso                                        0.19       0.37  52898.21
TransformedTargetRegressor                   0.19       0.37  52900.55
LinearRegression                             0.19       0.37  52900.55
OrthogonalMatchingPursuit                    0.19       0.37  52965.27
ElasticNet                                   0.19       0.37  53016.25
RANSACRegressor                              0.19       0.37  53073.53
GradientBoostingRegressor                    0.16       0.35  53907.22
PoissonRegressor                             0.15       0.34  54233.11
TweedieRegressor                             0.14       0.33  54504.60
Lars                                         0.13       0.33  54777.50
RandomForestRegressor                        0.12       0.32  55200.69
GammaRegressor                               0.10       0.30  55924.75
BaggingRegressor                             0.08       0.29  56328.68
XGBRegressor                                 0.04       0.25  57730.58
KNeighborsRegressor                          0.02       0.24  58186.55
LGBMRegressor                               -0.06       0.17  60627.12
HistGradientBoostingRegressor               -0.06       0.17  60627.12
AdaBoostRegressor                           -0.11       0.14  61938.64
ElasticNetCV                                -0.24       0.04  65458.88
DecisionTreeRegressor                       -0.27       0.02  66207.60
ExtraTreesRegressor                         -0.29      -0.00  66737.20
DummyRegressor                              -0.29      -0.00  66752.90
NuSVR                                       -0.30      -0.01  67177.31
SVR                                         -0.32      -0.03  67675.41
QuantileRegressor                           -0.32      -0.03  67685.83
ExtraTreeRegressor                          -0.36      -0.06  68674.52
GaussianProcessRegressor                    -0.76      -0.37  78131.32
KernelRidge                                 -3.73      -2.68 127934.90
LinearSVR                                   -4.04      -2.92 132103.18
MLPRegressor                                -4.06      -2.93 132356.36

                               Time Taken
Model
OrthogonalMatchingPursuitCV          0.01
LassoLarsCV                          0.01
LassoCV                              0.03
HuberRegressor                       0.01
LarsCV                               0.01
BayesianRidge                        0.01
LassoLarsIC                          0.01
RidgeCV                              0.00
LassoLars                            0.01
Ridge                                0.00
SGDRegressor                         0.01
PassiveAggressiveRegressor           0.03
Lasso                                0.00
TransformedTargetRegressor           0.00
LinearRegression                     0.00
OrthogonalMatchingPursuit            0.00
ElasticNet                           0.00
RANSACRegressor                      0.02
GradientBoostingRegressor            0.02
PoissonRegressor                     0.01
TweedieRegressor                     0.00
Lars                                 0.01
RandomForestRegressor                0.09
GammaRegressor                       0.01
BaggingRegressor                     0.01
XGBRegressor                         0.19
KNeighborsRegressor                  0.01
LGBMRegressor                        0.17
HistGradientBoostingRegressor        0.11
AdaBoostRegressor                    0.02
ElasticNetCV                         0.02
DecisionTreeRegressor                0.00
ExtraTreesRegressor                  0.08
DummyRegressor                       0.00
NuSVR                                0.01
SVR                                  0.02
QuantileRegressor                    0.69
ExtraTreeRegressor                   0.00
GaussianProcessRegressor             0.01
KernelRidge                          0.01
LinearSVR                            0.00
MLPRegressor                         0.15

In [ ]:
X_test.info()

In [ ]:
testeo.info()

In [ ]:
pred_lgbmr=lgbmr.predict(testeo)

In [ ]:
#pred_lgbmr=pd.DataFrame(pred_lgbmr, columns=['salary_in_usd'])
#pred_lgbmr.to_csv('lgbmr.csv',index_label='id')

In [81]:
pred_gbr=gbr.predict(testeo)

In [82]:
pred_gbr=pd.DataFrame(pred_gbr, columns=['salary_in_usd'])
pred_gbr.to_csv('gbr.csv',index_label='id')

In [83]:
pred_ridge=ridge.predict(testeo)

In [84]:
pred_ridge=pd.DataFrame(pred_ridge, columns=['salary_in_usd'])
pred_ridge.to_csv('ridge.csv',index_label='id')

In [ ]:
pred_ctr=ctr.predict(testeo)

In [ ]:
#pred_ctr=pd.DataFrame(pred_ctr, columns=['salary_in_usd'])
#pred_ctr.to_csv('ctr.csv',index_label='id')

In [ ]:
pred_pr=pr.predict(testeo)

In [ ]:
pred_pr=pd.DataFrame(pred_pr, columns=['salary_in_usd'])
pred_pr.to_csv('pr.csv',index_label='id')